"""Add bot_message_id to Payment table

Revision ID: 08aa6047beab
Revises: bb3403ea9ec2
Create Date: 2025-11-13 15:43:37.970689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08aa6047beab'
down_revision: Union[str, Sequence[str], None] = 'bb3403ea9ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('bot_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'bot_message_id')
    # ### end Alembic commands ###
