"""add system_settings table and manual_review status

Revision ID: 913fc275a6bb
Revises: 892c3dc6c75d
Create Date: 2025-11-24 01:46:34.934015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '913fc275a6bb'
down_revision: Union[str, Sequence[str], None] = '892c3dc6c75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE paymentstatus ADD VALUE 'manual_review'")
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manual_payment_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'manual_payments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('photo_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('verified_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('verified_by', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('payments', 'yookassa_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE payments SET yookassa_id = '' WHERE yookassa_id IS NULL")
    op.alter_column('payments', 'yookassa_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('manual_payments')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
