"""Add invite_link to subscriptions table

Revision ID: a10f1a517696
Revises: bd27a412cd67
Create Date: 2025-11-12 14:15:23.123977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10f1a517696'
down_revision: Union[str, Sequence[str], None] = 'bd27a412cd67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('invite_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'invite_link')
    # ### end Alembic commands ###
