"""Add last_warning_sent to subscriptions

Revision ID: bb3403ea9ec2
Revises: a10f1a517696
Create Date: 2025-11-12 23:06:27.571773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3403ea9ec2'
down_revision: Union[str, Sequence[str], None] = 'a10f1a517696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('last_warning_sent', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'last_warning_sent')
    # ### end Alembic commands ###
