"""add amount_paid to payment

Revision ID: e284015b7096
Revises: 913fc275a6bb
Create Date: 2025-11-24 01:52:26.366593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e284015b7096'
down_revision: Union[str, Sequence[str], None] = '913fc275a6bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount_paid', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'amount_paid')
    # ### end Alembic commands ###
